### PR TITLE
Automated TOC generation.

### PR DESCRIPTION
**Pull request by thatrandomperson5**
Re-opening of https://github.com/zevv/npeg/pull/55

In the README the auto TOC is generated between `<!-- AutoContentStart -->` and `<!-- AutoContentEnd -->` comments. The workflow only runs when the README is updated, and opens a pull request. This Is a safety precaution but it can be configured to directly commit.
If there are any issues please report them [here](https://github.com/thatrandomperson5/AutoMarkdownContents/issues).

I hope this is helpful!

### CODE REVIEW

**Comment by zevv** [comment]
Let's merge and give it a spin, thanks!

**Comment by zevv** [comment]
I merged but reverted because the results were a bit messy; Could you please rebase & squash the commits on latest master so we can do a clean merge?

**Comment by thatrandomperson5** [comment]
I don’t use git much but could you tell me the command for that chart? I think I rebased but I would have to check if it is cleaner.

**Comment by zevv** [comment]
It's always a bit of a hassle; I'll do it on my side, no problem.

**Comment by zevv** [comment]
So, I added the `contents.yml` and magically got a TOC. nice.

**Comment by zevv** [comment]
Any idea why the job failed now? https://github.com/zevv/npeg/actions/runs/3867859741

**Comment by thatrandomperson5** [comment]
> Any idea why the job failed now? https://github.com/zevv/npeg/actions/runs/3867859741
@zevv yes! it is solved here: https://github.com/peter-evans/create-pull-request/issues/707 
Just replace
```yml
name: Make table of contents
on: 
  push:
    paths:
      - README.md
 ```
 in contents.yml with
```yml
name: Make table of contents
on: 
  push:
    paths:
      - README.md
    branches:
      - '**' 
```
Although this means it will not run on releases.

**Comment by zevv** [comment]
ok, changed that, let's see how this works. Thanks!

**Comment by thatrandomperson5** [comment]
> ok, changed that, let's see how this works. Thanks!

It seems you made a small mistake!
`- '**' name: Make table of contents` should be `- '**'`

**Comment by zevv** [comment]
Yeah, I noticed, just fixed that.

**Comment by zevv** [comment]
You'll never guess what I just learned... 

ff

**Comment by thatrandomperson5** [comment]
Lol, i did not that existed, at least it still helps on nimble: https://nimble.directory/pkg/npeg

**Pull request closed without merging**
